id: P1C427A97
initial_creation_type: input
source_metadata:
  title: Nāgārjuna
  language: es
  description: 'Texts by and about the great Indian philosopher-saint Ārya Nāgārjuna
    (''phags pa klu sgrub, c.150 – c.250 CE), known to Tibetans as the founder of
    the tradition of Profound View (zab mo lta ba):'
  volume:
    3b5657bd958a426ea100d6cfedab869c:
      title: Commentary on the Noble Essence of the Dharmadhātu
      parent: Dependent Origination
    0e440f777b58422f96ea0496166d01a3:
      title: Verses on the Heart of Dependent Origination
      parent: Dependent Origination
    c347f2aab9084371ae3ad6ac5fbf083d:
      title: In Praise of the Twelve Deeds of the Buddha
      parent: Praise
    0fe44e7d9873482a93e01bbafc82f60d:
      title: 'Praise of the Buddha: With Skilful Means & Compassion...'
      parent: Praise
    d2ac9f9fb0184880968d0c6ca4777ce9:
      title: Ultimate Praise of the Noble and Venerable Mañjuśrī
      parent: Praise
created_at: '2022-03-01T02:18:03.538700'
last_modified_at: '2022-03-01T02:18:03.538702'
